# Dependencies
markdown:  redcarpet
highlighter:  rouge
excerpt_separator: <!--more-->

# Permalinks
permalink:        pretty

# Setup
title:    Realfiction
tagline:    'intersect'
description:  'Content from Frank Quednau about programming and fields of interest.'
url:    http://realfiction.net
baseurl:  /

author:
  name:        'Frank Quednau'
  url:            https://twitter.com/fquednau

paginate:         5

redcarpet:
  extensions: []

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/hyde

gems:
  - jekyll-redirect-from
